### ISSUE TITLE
Problem with pipeline - warning messages and eventual crash

### ISSUE THREAD

**Issue by michael-imbeault** [guanjue/S3V2_IDEAS_ESMP#2]
Running the pipeline on a set of H3K9me3 (single mark, 120 files), the pipeline proceeds through the initial steps and everything is fine until:

Get S3norm normalized read counts......
Read 14311406 items
Warning message:
In min(d2_cpk[d2_cpk > 0]) : no non-missing arguments to min; returning Inf
Read 14311406 items
Warning message:
In min(d2_cpk[d2_cpk > 0]) : no non-missing arguments to min; returning Inf
Read 14311406 items
Warning message:
In min(d2_cpk[d2_cpk > 0]) : no non-missing arguments to min; returning Inf
Read 14311406 items

And then:

Read 14311406 items
Warning message:
In min(d2_cpk[d2_cpk > 0]) : no non-missing arguments to min; returning Inf
[1] "ref peak num"
[1] 322676
[1] "tar peak num"
[1] 349187
    Mode    FALSE     TRUE     NA's
 logical 13962219   349187        0
    Mode    FALSE     TRUE     NA's
 logical 13962219   349187        0
Read 14311406 items
Warning message:
In min(d2_cpk[d2_cpk > 0]) : no non-missing arguments to min; returning Inf
Read 14311406 items
[1] "ref peak num"
[1] 322676
[1] "tar peak num"
[1] 301943
Warning message:
In min(d2_cpk[d2_cpk > 0]) : no non-missing arguments to min; returning Inf
    Mode    FALSE     TRUE     NA's
 logical 14009463   301943        0
    Mode    FALSE     TRUE     NA's
 logical 14009463   301943        0
[1] "ref peak num"
[1] 322676
[1] "tar peak num"
[1] 283096
    Mode    FALSE     TRUE     NA's
 logical 14028310   283096        0
    Mode    FALSE     TRUE     NA's
 logical 14028310   283096        0
Read 14311406 items

And then fails because it didn't generate files correctly (probably because of warnings above):

Error in fread(toString(file_list[1, 1])) :
  File 'E001_0.H3K9me3.S3V2.bedgraph' does not exist or is non-readable. getwd()=='/rds/project/mi339/rds-mi339-kzfps/users/michael/NIH_Roadmap/output'
Calls: as.data.frame -> fread

Let me know if you need more data to troubleshoot this - was running on an HPC with 4 thread 48GB of memory.

**Comment by guanjue** [comment]
This is an error caused by no common peaks (based on fdr) across all 120 data sets. I modified the script to circumvent this problem by replacing the common peak across all data set by the common peak of two data sets when no common peaks are identified. So please re-pull the github and this issue should be solved.

**Comment by michael-imbeault** [comment]
OK - it did move one to other sections without warnings with the new code - however it hit another block later:

[1] "E124.H3K9me3.121.ctrl.idsort.bedgraph"
[1] "E125.H3K9me3.122.ctrl.idsort.bedgraph"
[1] "E126.H3K9me3.123.ctrl.idsort.bedgraph"
[1] "E127.H3K9me3.124.ctrl.idsort.bedgraph"
[1] "E128.H3K9me3.125.ctrl.idsort.bedgraph"
[1] "E129.H3K9me3.126.ctrl.idsort.bedgraph"
[1] 1
[1] 0
[1] "read average signal"
Read 14311406 items
[1] 13768274
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.0000  0.3767  0.4626  0.4725  0.5679  1.0000
[1] 13768274
[1] "Summary signal"
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.00000 0.00000 0.00000 0.05263 0.00000 7.60600
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
      0       0       0       0       0       0
Error in if (p < 0.001) { : missing value where TRUE/FALSE needed
Calls: get_true_NB_prob_size
Execution halted
cut: E001_0.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory
cut: E002_1.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory
cut: E003_2.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory
cut: E004_3.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory
cut: E005_4.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory
cut: E006_5.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory

**Comment by guanjue** [comment]
This error created because the signals of common background regions of the average signal track are all 0 which failed to generated a background model.

I wonder if you can send me the following files?

H3K9me3.average_sig.bedgraph.S3V2.ave.bedgraph
H3K9me3.average_sig.bedgraph.S3.bedgraph

two or three files ended with "*.ip.idsort.bedgraph"

**Comment by michael-imbeault** [comment]
Cleared the results directories from the previous failed runs and now it went through the normalized bigwig creation, which is what I really wanted out of this.

Crashed a bit further down with:

for average signal
for S3V2 -log10 p-value
sort: cannot read: E017_16.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory
sort: cannot read: E001_0.H3K9me3.S3V2.bedgraph.NBP.bedgraph: No such file or directory

**Comment by michael-imbeault** [comment]
The files come from NIH Roadmap, and can be downloaded from: https://egg2.wustl.edu/roadmap/data/byFileType/signal/consolidated/macs2signal/foldChange/

**Comment by guanjue** [comment]
Thanks for the information. 

The pipeline is designed for average read counts of each 200-bp bin. 
So in the problematic step, it needs to learn a negative binomial model from the common background regions of the average signal track. In this case, all of the common background regions have signal (fold-change) below 1. As a result, the negative binomial model cannot be learnt. 

I have made some modifications in the pipeline, so that when all signal in common background regions are below 1, it will use all regions to learn the background model.

**Comment by michael-imbeault** [comment]
Interesting - in this case sadly the bigwig files are not the reads themselves directly, but its common that all sorts of manipulations are done to public bigwig (signal substraction, etc). I'll run it again with your most recent changes - but better results would be obtained from a pure read count bigwig?

**Comment by guanjue** [comment]
Yes, the pure read count or the average read counts of certain window size would go through the pipeline with better results.
