### ISSUE TITLE
Assorted Questions

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [guanjue/S3V2_IDEAS_ESMP#3]
Kind greetings @guanjue, 

This is such an AWESOME TOOL which I discovered after looking at `IDEAS` and `IDEAS_2018`! 
I'm interested in applying it to 100's of samples worth of data related to Huntington's Disease.

I would greatly appreciate if you can answer these questions! :) 

* Would you recommend using this over the original `IDEAS` or `IDEAS_2018` repo?

* What exactly is the `cell type ID`? As well, in your example [here](https://github.com/guanjue/S3V2_IDEAS_ESMP/blob/master/manuals/inoutput_for_S3V2_IDEAS_pipeline.md#5th-column-absolute-path-to-the-control-bigwig-files-if-there-is-no-control-signal-track-this-column-can-be-leave-as-empty), how can two different human cell types (`CMP` and `ERY_fl`) have the same `cell type ID`?

* Is the 5th column in the input metadata list meant to be `"Input" BigWig` (i.e. the regions that are PCR-transcribed without antibody specificity)?

* If you have multiple replicates for a specific mark and cell line, how to include that in the input?

* By `"common foreground"` or `"common peaks"` you're saying regions that are enriched but unlikely to be `"differential"`?
I ask since I was worried that some of these `"common peak"` regions are actually peaks where it is differential signal between disease and control. 
That would be problematic to normalize and remove that true biological signal if so. 

* Within each `200bp region` (example region size from paper), are you looking at `"common foreground/peaks"` across all marks? (i.e. are the dots on the scatterplot figure from `Figure 1A` coming from all the input marks + `ATAC-Seq`)?

* With `S3V2`, once you split reads within each bin into foreground/background, why do you end up with `"common peaks"`  in `Figure 1A` for `S3V2_IDEAS` paper?
I thought `S3V2` removes the peak vs background and goes with foreground vs background?

* How does `S3V2` determine which of many cell types is a `"reference"` and which are the `"targets"`?

**Comment by guanjue** [comment]
Thank you for interested in this pipeline.

Here are my answers to your questions:
(1) Would you recommend using this over the original IDEAS or IDEAS_2018 repo?
The S3V2-IDEAS is the recommended one because it incorporate the S3V2 normalization and it is easier to run. 
The IDEAS part for S3V2_IDEAS and IDEAS_2018 are the same. In your case, if you want to normalize the signal in your way, the IDEAS_2018 may be better to use.

(2) What exactly is the cell type ID? As well, in your example here, how can two different human cell types (CMP and ERY_fl) have the same cell type ID?
In the metadata, the 1st column is the cell type name. The 3rd column (cell type replicate id) is the bio-replicate id for the same cell type. 

(3) Is the 5th column in the input metadata list meant to be "Input" BigWig (i.e. the regions that are PCR-transcribed without antibody specificity)?
Yes, it should be the bigwig file for the no antibody control sample. But if there is no control sample, it can be left empty.

(4) If you have multiple replicates for a specific mark and cell line, how to include that in the input?
Unfortunately, the S3V2-IDEAS pipeline can only treat different replicates as different bio-samples. So I suggest to merge the replicate bigwig files by taking the average. 

(5) By "common foreground" or "common peaks" you're saying regions that are enriched but unlikely to be "differential"?
    I ask since I was worried that some of these "common peak" regions are actually peaks where it is differential signal between disease and control.
    That would be problematic to normalize and remove that true biological signal if so.
I agree that is a issue for using the S3V2 normalization method. 
In one of our collaborate project (https://pubmed.ncbi.nlm.nih.gov/33626344/), we were analyzing CTCF signal after AID degradation treatment. Because the CTCF signals were expected to decrease after the treatment, we did not use the S3V2 for normalization. Instead, we first selected dozens of regions, we then use the CTCF-qPRC signal at different time point as the reference  for normalization.

(6) Within each 200bp region (example region size from paper), are you looking at "common foreground/peaks" across all marks? (i.e. are the dots on the scatterplot figure from Figure 1A coming from all the input marks + ATAC-Seq)?
No, the common peak regions are the common peaks for the same mark. The figure1A is just showing the one mark's signal (CTCF) of two cell types.
The pipeline includes two step way for the normalization. 
Step1: For each mark, the pipeline will get an average signal track first. It will then normalize each mark's average signal track to one global reference track (provided in the pipeline).
Step2: the pipeline will normalized each samples of the same mark against the normalized average signal track (mark1_normalized_average_track) in step 1.


(7) With S3V2, once you split reads within each bin into foreground/background, why do you end up with "common peaks" in Figure 1A for S3V2_IDEAS paper?
    I thought S3V2 removes the peak vs background and goes with foreground vs background?
The S3V2 is still using the common peak and common background as the anchor regions. It still assume the signals in different sample in those two regions have similar signal levels. Splitting reads within each bin into foreground/background can allow us to adjust mean and variance differently for the foreground signal and background signals.

(8) How does S3V2 determine which of many cell types is a "reference" and which are the "targets"?
For each mark, the average signal track across all cell types are used as reference. The different cell types are all treated as target. 

Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
Hello @guanjue , 

I just wanted to give a special mention to you! 
We need more diamonds 💎 like yourself in the open-source Bioinformatics community. 

Your quick response and willingness to answer all questions is greatly appreciated! 

I have a few more questions that are really important as I slowly try to understand and utilize `IDEAS` (still unsure if I will use this or `IDEAS_2018`). 

* With regard to TECHNICAL replicates for a specific cell and mark...
I actually found something in the attached file [readme_ideas.txt](https://github.com/guanjue/S3V2_IDEAS_ESMP/files/6971724/readme_ideas.txt) from the original `IDEAS` repo. 
The author there says "	If you have replicate data, you can have identical cell type names and factor names in the first two columns, but the file name in the 3rd column, of course, should be unique."

Shouldn't the above statement apply to `IDEAS_2018`?
Hence, I can use TECHNICAL replicates by giving the unique filename?

* In the example within the repo, you segmented the ENTIRE genome in 200bp in your input BED file.
Why did you choose 200bp region as opposed to another number (e.g. 500bp regions)?
Why would you use 200bp segments of the ENTIRE genome when most regions won't have peaks and hence, are non-active/uninteresting regions?

* To create an input BED file of regions that I want to know the Epigenomic state for, I used `DiffBind` in the following way. 
I created a `DiffBind object (DBA)` with all ChIP-Seq marks across all cell types and including all technical replicates for each cell and mark. 
`DiffBind` takes all the peak regions across all the cells and marks and merges overlapping regions.
It automatically filters out regions that do not have any existence in any other technical replicates (i.e. inaccurate replicate-specific signal).
With this list of overlapping-merged-regions, I took those regions where there are AT LEAST 2 non-zero read counts across all cell lines and marks.

This list includes 173,581 unique regions. 
The median length of the regions is 1967bp and the mean is 12,976bp (i.e. skewed tail of length distribution). 

Is this input BED list too long for `IDEAS`?
Are the regions I want to know the state of too long?

* What's the specific benefit to adding ATAC-Seq? 
How does program know this is meant to be genome-wide vs very-specific (ChIP-Seq)?

**Comment by guanjue** [comment]
Thanks for the comments!

(1) Shouldn't the above statement apply to IDEAS_2018? Hence, I can use TECHNICAL replicates by giving the unique filename?
Yes, it should work for IDEAS_2018. But the code for IDEAS is mainly wrote by Dr. Yu Zhang, so I didn't try to the directly input separate technical replicates for IDEAS before. 
For the S3V2_IDEAS pipeline, it can run the normalization and generate the IDEAS input files (*sh, *input, *parafile files for running IDEAS) in the output folder.  They can also be easily modified to run the IDEAS with the  technical replicates separate.

(2) Why did you choose 200bp region as opposed to another number (e.g. 500bp regions)?
We choose 200bp is because each 200bp is around the size of a nucleosome. 
IDEAS can work on larger bin size. However, the caveat is very large bin size may mix the epigenetic profiles of multiple nucleosomes, which may create epigenetic state pattern that is not really exist. 

(3) Why would you use 200bp segments of the ENTIRE genome when most regions won't have peaks and hence, are non-active/uninteresting regions?
Yes, most of the regions on the genome will be clustered as quiescent state. Focusing on peak regions can greatly improve the computing speed and resource.
But for peak calling, the boundary of the peaks and the number of peaks are often determined by the threshold of the peak calling step. We run the IDEAS genome segmentation on the entire genome because the state will be defined by the posterior probability which will not influenced by the peak calling step. 

(4) This list includes 173,581 unique regions.
The median length of the regions is 1967bp and the mean is 12,976bp (i.e. skewed tail of length distribution).
Is this input BED list too long for IDEAS? Are the regions I want to know the state of too long?
This peaks size is a little bit too large which will probably create states with mixed marks. Also your peak have different sizes. For IDEAS, it is better to have the same bin size, because different bin size will create different signal-to-noise ratio which may create different artificial state. One way do this is to split larger peaks into multiple same size bins. After the IDEAS run, the states' coverage of the peaks can be used to cluster the peaks.

(5) What's the specific benefit to adding ATAC-Seq?
The ATAC-seq is a very informative mark. It can capture some accessible regions without any other marks. Following the differentiation path, we did observe those regions can gradually add H3K4me1, then add H3K27ac in the downstream cell types. Also in other study (https://doi.org/10.1016/j.bbagrm.2019.194443), the ATAC-seq pattern reflect the TF binding pattern is the downstream differentiated cell types.

(6) How does program know this is meant to be genome-wide vs very-specific (ChIP-Seq)?
The program doesn't know if it is genome-wide or peak-specific.

**Comment by YogiOnBioinformatics** [comment]
Thanks for answering all these questions @guanjue !!!!!
I only have a FEW MORE and then I think I'm READY to use this program. 

* _"However, the caveat is very large bin size may mix the epigenetic profiles of multiple nucleosomes, which may create epigenetic state pattern that is not really exist."_
I understand we don't want the regions to be TOO LARGE. 
But, I'm trying to think if 200bp regions makes sense biologically because I don't see why the epigenetic state of a region has to be specific to a 200bp region. 
Why can't epigenetic states go past a per-nucleosome basis and hence you could have regions that are 600-1k bp long that are, for example, enhancers or promoters?
There is clear evidence that certain promoter/enhancer regions are over 500bp which is more than one nucleosome in length.  Obviously, enhancers/promoters aren't going to be bound by nucleosomes but I'm highlighting why 200bp is confusing me when there exist epigenetically active regions that are longer than that. 

* _"We run the IDEAS genome segmentation on the entire genome because the state will be defined by the posterior probability which will not influenced by the peak calling step."_
That makes total sense but still it WOULDN'T be wrong to use the peak regions, correct?

* _"...which will probably create states with mixed marks."_
Instead of "states with mixed marks", do you mean to say a state that is "mixed" (has no clear or biologically valid definition)?
If not, please read below since I may have a FUNDAMENTAL confusion. 
The creation of epigenetic states is based on the fact that multiple different marks are within proximity and hence, that creates a special state. 
For example, if H3K4me1 and H3K4me3 are in the same vicinity but the concentration of H3K4me1 is MUCH HIGHER, it's an enhancer-like region.
The very fact that multiple marks CAN be significantly available in a specific location gives the possibility of understanding the complex epigenetic state it is in. 
A 200bp region being assigned State 24 (PENCA) from this [figure](https://raw.githubusercontent.com/guanjue/IDEAS_2018/master/example_figures/f3_vision_result.png) is because multiple marks were active in that 200bp region.
Isn't State 24 a "state with mixed marks"?

* _"After the IDEAS run, the states' coverage of the peaks can be used to cluster the peaks."_
Just trying to understand what you mean here.
Let's say that I had a region that was 3k bp which I broke up into 6 500bp segments.
Are you saying that once I get the `IDEAS`-derived epigenetic state for EACH 500bp region, that I could somehow use that info to make a conclusion about the 3k bp region via clustering?

* _"The program doesn't know if it is genome-wide or peak-specific."_
Sorry, let me actually use an example to ask a FUNDAMENTAL question.
When you input "H3K4me1" into the input metadata sheet, is `IDEAS` programmed beforehand to know that this mark is meant to be about enhancers?
More generally, is `IDEAS` pre-programmed to know the basics of what each INDIVIDUAL mark/ATAC-Seq is meant to inform? (e.g. H3K27Ac is "Active Enhancer", H3K27me3 is "Heterochromatin", etc.)

**Comment by guanjue** [comment]
(1) Why can't epigenetic states go past a per-nucleosome basis and hence you could have regions that are 600-1k bp long that are, for example, enhancers or promoters?
Yes, most of the regulatory elements are larger than 200bp. But those longer regions can always be represented by multiple small size bins. Later the peak state can be defined as the the non-quiescent state covers the highest proportion of the peak.
But for the larger peaks, some nearby elements maybe covered by the same larger peak, especially at the boundary between two elements. In those case the most problematic state will be the state with both active mark and repressed mark (e.g. state with both H3K27ac and H3K9me3) which are actually located in different but nearby position. And that problematic information cannot be identified based on the epigenetic output.

I think it may be safer to have smaller bins. But it always depends on the actual result.


(2) That makes total sense but still it WOULDN'T be wrong to use the peak regions, correct?
That's right. But it is better to make the peaks share the same size to avoid create artificial signal-to-noise ratio.

(3) Instead of "states with mixed marks", do you mean to say a state that is "mixed" (has no clear or biologically valid definition)? Isn't State 24 a "state with mixed marks"?
I mean state that mixed of multiple states that located very close to each other. In our study, one of our main goal is to use epigenetic state to pinpoint potential target for cas9 knock-out, so we wanted to get state ideally without mixing multiple states for each nuleosome. 
But the mixed state is always depends on the resolution and the question you study. For the state 24, it is not defined as a mixed state based on the 200bp resolution. But if we zoom-in 50bp resolution, it may become a regions with a enhancer close to a promoter (we should but didn't really check it). In our analysis, it doesn't matter too much.
But for example if you are interested in to find the boundary between repressor and enhancer, then the problematic state in Q1 (with both H3K27ac and H3K9me3) may be the interesting targeted ones.


(4) Are you saying that once I get the IDEAS-derived epigenetic state for EACH 500bp region, that I could somehow use that info to make a conclusion about the 3k bp region via clustering?
Yes, same answer as Q1, e.g the non-quiescent state covers the highest proportion of each peak can be used as the peak's state.


(5) When you input "H3K4me1" into the input metadata sheet, is IDEAS programmed beforehand to know that this mark is meant to be about enhancers?
No, the IDEAS program does not know the function of each mark. The letter annotation in the figure is mannully labeled by Dr. Ross Hardison.

**Comment by YogiOnBioinformatics** [comment]
This pretty much answers all my questions and I'm ready to use the tool! 
Your patience and willingness to answer the questions is greatly appreciated!
I will make sure to utilize the MANY suggestions you've provided. 

You rock @guanjue ! 🥇 

A question I can ask that does not block my analysis... 

If the program has no clue what a specific mark is supposed to do, what's the basis to say this tool works?

E.g. if the program has no clue that H3K27me3 is indicative of heterochromatic formation and you have a 200bp region with ONLY H3K27me3 signal, how will it know to assign the state that means "likely heterochromatin"?

**Comment by guanjue** [comment]
Do you mean how does the state get the letter based function label? (e.g The state 3 in the figure got the "Pc" label stands for Polycomb)
If this is your question, my answer is as follows:
The IDEAS only knows the "200bp region with ONLY H3K27me3 signal" belongs to state 3 (which is a cluster of regions with only H3K27me3 signal). The "Pc" label was added After the IDEAS run based on prior knowledge about the function of the H3K27me3 mark in literature.

**Comment by YogiOnBioinformatics** [comment]
Ah ok never mind. 
The user has to make the functional annotation of the state. 

Once again, you're a diamond 💎  @guanjue!!!

Really great talking with you and appreciate all your help! 
If I need anything else specific, I'll start a new issue. 

Closing this issue.
