### ISSUE TITLE
With the same input data and the same parameters, the output is not the same

### ISSUE THREAD

**Issue by fatyang799** [guanjue/S3V2_IDEAS_ESMP#5]
I run the S3V2 package with same input bigwig file and same parameters 27 times. But the number of chromatin states is not even close. The figure below shows the number of chromatin states obtained for each run:
![image](https://user-images.githubusercontent.com/52167840/175275803-7585504f-09ee-43ff-981d-0f8c4cbe358b.png)
> x axis: n-th to run the code.
> y axis: the number of chromatin states obtained for each run.

This result confuses me. I would like to know why this is happening and if it is possible to make the results reproducible. I mean run the code with same input data and same parameters, and get same or similar result each time.

**Comment by guanjue** [comment]
This is due to the internal random initialization step and the MCMC step inside IDEAS model. The IDEAS will randomly select N 50MB regions to generate an initial set of state and then select the state that are reproducible 50% of the N times for downstream analysis. 

To reduce this issue can be reduced, you can select the initial states with higher reproducibility for downstream analysis:
This can be done by change the 466 line in the following two files 
"S3V2_IDEAS_ESMP/python_pipe/bin/IDEAS_2018/bin/ideaspipe.R"
"S3V2_IDEAS_ESMP/python_pipe/bin/IDEAS_2018/bin/ideaspipe_np.R"
from "mycut=0.5" to "mycut=0.9" (or any other reproducible rate to achieve your preferred set of states, but keep in mind the caveat is you may miss some less abundant states.)

This setting can reduce the reproducible issue in the final output. However, since I didn't code the IDEAS model part, so there may still have some difference between each run. 

Also, can you share one of your .parafile file in your output folder? 
And how many epigenetic features do you have? 65 states is a pretty large number of states. Based on our previous analysis of 8 features (ATAC, CTCF, 6 histone marks), the state number around 30 may be more reasonable.

Best wishes.
Guanjue

**Comment by fatyang799** [comment]
Hi Guanjue:

Thanks for your quick response!

Right now, I have about 25 epigenetic features. The `.parafile` file I might share with you later. Because recently I have to leave the lab for a while. I could share `.parafile` file with you when I go back to lab.

Best wishes.
Liu

**Comment by fatyang799** [comment]
I'm sorry for not uploading the file to share with you for so long. During this time, I was hospitalized for healthy reasons.

We downloaded all data from ENCODE database. In the attachment is the `.para0` file (I guess this file may be the formal one?).

At the same time, I think the IDEAS package may need to have a more detailed description of the output results. So far I can only get a general idea of my results through the `ID_name.pdf` file, but I don't know which file the `ID_name.pdf` file is based on, I guess it should be the `.para` file. Meanwhile, I do not know **what is differences between**  `.para`  and  `.para0`. We would appreciate it if you could explain the meaning of these files.

Also, **it is difficult to understand files under the output path** (`ID_name_IDEAS_output/`), such as what information is recorded in the `ID_name.profile` file, and how to understand these results. If you can have a more detailed description of these files, I believe more people will be happy to using IDEAS software.


[ENCODE_Markers.para0](https://github.com/guanjue/S3V2_IDEAS_ESMP/files/9125766/ENCODE_Markers.para0.txt)

**Comment by guanjue** [comment]
No worries. Hope you have been getting now.

The *.para0 file is the reproducible states' information generated from the randomly select N 50MB regions.
The *.para file is the final IDEAS states information after the MCMC.
The ID_name.pdf is based on the *.para file (in your case, it should be ENCODE_Markers.para file.)
You can get the state score matrix by using each feature's column divided by the first column:
```
d = read.table('ENCODE_Markers.para', header=T, sep=' ', comment.char='~')
ds = d[,2:(num_of_features+1)] / d[,1]
```
For the profile file, It is directly output from IDEAS. But I am not sure what information it recorded.

Thanks for the suggestions, we will add more descriptions about output files.

Best wishes.
Guanjue
