### ISSUE TITLE
how s3norm deal with normalization across various markers?

### ISSUE THREAD

**Issue by fatyang799** [guanjue/S3V2_IDEAS_ESMP#7]
Hi Guanjue,

I read again the S3norm paper published in the NAR journal (DOI: 10.1093/nar/gkaa105). And I understand the core mechanism of s3norm, but some details still confuse me.

In my understanding, s3norm will first get average signal for each epigenomic marker as reference. Then all data within same marker group will be nonlinear transformed. This has normalized the signal across identical marker group. 

Then, how does s3norm deal with the signal across various marker group? For example, I get the normalized H3K4me3 signals and normalized H3K27me3 signals. After this, how s3norm solve the comparable problem between H3K4me3 signals and H3K27me3 signals? What is the rationale/mechanism of this treatment?

Thanks!

**Comment by guanjue** [comment]
For cross-mark normalization, we use an exponential transformation in
S3norm to normalize the data so that the means of *ALL peak regions*
between two marks and also the means of non-peak regions between the two
marks to be matched. For each mark, the sets of peak regions were
identified independently.

For normalizing the data of the same mark, the difference is to match the
"the means of *COMMON peak regions*..."

The rationale is to match the signal level so that they can be more
comparable with generating the epigenetic states. The caveat of this
strategy is the number of peaks in different marks may influence the make
signal-to-noise ratio somehow differently, however, we don't have a more
reasonable strategy for this issue.

Best wishes.
Guanjue

**Comment by fatyang799** [comment]
Thanks for your rapid and clear explanation! 
I have understood what s3norm has done for my data. 

Best wishes!
