### ISSUE TITLE
`${ID}_IDEAS_input_NB` output files have `NAs`

### ISSUE THREAD

**Issue by fatyang799** [guanjue/S3V2_IDEAS_ESMP#8]
why `${ID}_IDEAS_input_NB` output files have `NAs`?

Recently, I run the s3v2 package to normalize the histone marker ChIPseq and ATACseq data. The output files in `${ID}_IDEAS_input_NB` directory seems strange since there are lots of `NA` in several output files. I don't understand why I got the `NA` in the results. As shown in the picture below.

(Note: I have already removed the blacklist regions.)

![image](https://user-images.githubusercontent.com/52167840/224877740-19e3930a-12ed-4d34-804d-88500e108375.png)

**Comment by guanjue** [comment]
Hi, 

I haven't seen this error before.

I wonder If the corresponding ".S3V2.bedgraph" files also have NAs in the 4th column at these rows? It seems that some of the files are not incomplete.

If so, please try to use these settings to make sure all signal tracks were generated completely.
get_sigtrack='T'
normalization='F'
get_bw='F'
run_ideas='F'

Also please use threads=1, so that the parallel step will not cause conflict(which happened in some other people's runs). 

Best wishes.
Guanjue

**Comment by fatyang799** [comment]
> Hi,
> 
> I haven't seen this error before.
> 
> I wonder If the corresponding ".S3V2.bedgraph" files also have NAs in the 4th column at these rows? It seems that some of the files are not incomplete.
> 
> If so, please try to use these settings to make sure all signal tracks were generated completely. get_sigtrack='T' normalization='F' get_bw='F' run_ideas='F'
> 
> Also please use threads=1, so that the parallel step will not cause conflict(which happened in some other people's runs).
> 
> Best wishes. Guanjue

Sorry I may not understand what you mean by saying "corresponding `.S3V2.bedgraph" files`"? Because I can not find a file named "*.S3V2.bedgraph". I only have files named "${cell}_${id}.${marker}.S3V2.bedgraph.info.txt" in the output directory.

Meanwhile, I also don't understand what you mean by saying "make sure all signal tracks were generated completely". If I set `normalization='F'`, I will not get the normalized output data. 

Or do you mean that I set 'TFFF' (in the same order as above) to run the program to get all signal tracks, and then set 'FTTT' to normalize and run IDEAS?

Many thanks.

**Comment by guanjue** [comment]
(1) Sorry I may not understand what you mean by saying "corresponding .S3V2.bedgraph" files"? Because I can not find a file named "*.S3V2.bedgraph". I only have files named "${cell}_${id}.${marker}.S3V2.bedgraph.info.txt" in the output directory.
Sorry, I forgot I remove these files to reduce the size of the output folder.So please remove the following lines in "S3V2_IDEAS_pipeline.py", and then use TTFF to regenerate these files.line 181-187a=call('rm *.bedgraph.norm.bedgraph', shell=True)
b=call('rm *.S3V2.bedgraph.NBP.bedgraph', shell=True)
c=call('rm *.S3V2.ave.bedgraph.NBP.bedgraph', shell=True)
d=call('rm *.bedgraph.S3.bedgraph', shell=True)
e=call('rm *.S3V2.bedgraph', shell=True)
f=call('rm *.S3V2.ave.bedgraph', shell=True)
g=call('rm *.average_sig.bedgraph', shell=True)

(2) Meanwhile, I also don't understand what you mean by saying "make sure all signal tracks were generated completely". If I set normalization='F', I will not get the normalized output data. I guess this may be cause by the "bigWigAverageOverBed" step generating the incomplete files. (but this may not be the case)

(3) Or do you mean that I set 'TFFF' (in the same order as above) to run the program to get all signal tracks, and then set 'FTTT' to normalize and run IDEAS?
Yes. so please use TTFF to get the output signal files, and then if everything looks good, use FFTT to get the bigwig and ideas outputs.

**Comment by fatyang799** [comment]
> (1) Sorry, I forgot I remove these files to reduce the size of the output folder.So please remove the following lines in "S3V2_IDEAS_pipeline.py", and then use TTFF to regenerate these files.line 181-187a=call('rm *.bedgraph.norm.bedgraph', shell=True)
> b=call('rm *.S3V2.bedgraph.NBP.bedgraph', shell=True)
> c=call('rm *.S3V2.ave.bedgraph.NBP.bedgraph', shell=True)
> d=call('rm *.bedgraph.S3.bedgraph', shell=True)
> e=call('rm *.S3V2.bedgraph', shell=True)
> f=call('rm *.S3V2.ave.bedgraph', shell=True)
> g=call('rm *.average_sig.bedgraph', shell=True)

yes, I check the code in `S3V2_IDEAS_pipeline.py`, and these code (line 181-187) exist in the script. So your code is right, don't worry.



> (2) I guess this may be cause by the "bigWigAverageOverBed" step generating the incomplete files. (but this may not be the case)

I may understand your concern. This should be relevant to the next note.



> (3) Yes. so please use TTFF to get the output signal files, and then if everything looks good, use FFTT to get the bigwig and ideas outputs.

I guess you suspect that there are some errors/warnings in the `bigWigAverageOverBed` step, so you suggest that I do the normalization separately (TTFF). After normalization, do the `bigWigAverageOverBed` step to get input files for IDEAS. Do I understand this correctly?

**Comment by guanjue** [comment]
Yes, that's correct. 
To be a bit more conservative, may be it is better to first try TFFF, then FTFF, and then FFTT

**Comment by fatyang799** [comment]
Thanks very much!
I will test the various strategies and let you know if I solve the problem!

**Comment by fatyang799** [comment]
Hi,

I have run the code with the same data set. There are two differences in that code compared to my previous version.

1. Threads parameter modified to 1, past threads set to 10
2. run `get_sigtrack`, `normalization`, `get_bw` and `run_ideas` part separately. (Right now, I have only run the `get_sigtrack` and  `normalization` part)

I compared the md5 value of output files in `${ID}_IDEAS_input_NB`. I got these information:

1. When `thread=1`, all files seem good, and no NA in the files.
2. The consuming time for output with `thread=10` and output with `thread=1` is almost identical.
3. The difference of md5 value between files with `thread=10` and files with `thread=1` is enriched on the first file within the same cell type and same marker.

With regard to point 3, I will give a simple example to illustrate the problem in concrete terms.

Suppose I have a metadata file as follows:

```
293T	H2AFZ	m1	/PATH/TO/DIR/H2AFZ.bw
293T	H2AFZ	m2	/PATH/TO/DIR/H2AFZ.bw
293T	H2AFZ	m3	/PATH/TO/DIR/H2AFZ.bw
293T	H3K27ac	m1	/PATH/TO/DIR/H3K27ac.bw
293T	H3K27ac	m2	/PATH/TO/DIR/H3K27ac.bw
293T	H3K4me3	m1	/PATH/TO/DIR/H3K4me3.bw
293T	H3K4me3	m2	/PATH/TO/DIR/H3K4me3.bw
293T	H3K4me3	m3	/PATH/TO/DIR/H3K4me3.bw
293T	H3K4me1	m1	/PATH/TO/DIR/H3K4me1.bw
293T	H3K4me1	m2	/PATH/TO/DIR/H3K4me1.bw
293T	H3K9me3	m1	/PATH/TO/DIR/H3K9me3.bw
293T	H3K9me3	m2	/PATH/TO/DIR/H3K9me3.bw
293T	H3K36me3	m1	/PATH/TO/DIR/H3K36me3.bw
293T	H3K36me3	m2	/PATH/TO/DIR/H3K36me3.bw
THP1	H2AFZ	m1	/PATH/TO/DIR/H2AFZ.bw
THP1	H2AFZ	m2	/PATH/TO/DIR/H2AFZ.bw
THP1	H3K14ac	m1	/PATH/TO/DIR/H3K14ac.bw
THP1	H3K4me3	m1	/PATH/TO/DIR/H3K4me3.bw
THP1	H3K4me3	m2	/PATH/TO/DIR/H3K4me3.bw
THP1	H3K4me1	m1	/PATH/TO/DIR/H3K4me1.bw
THP1	H3K9me3	m1	/PATH/TO/DIR/H3K9me3.bw
THP1	H3K9me3	m2	/PATH/TO/DIR/H3K9me3.bw
THP1	H3K27ac	m1	/PATH/TO/DIR/H3K27ac.bw
THP1	H3K27ac	m2	/PATH/TO/DIR/H3K27ac.bw
THP1	H3K27ac	m3	/PATH/TO/DIR/H3K27ac.bw
THP1	H3K27me3	m1	/PATH/TO/DIR/H3K27me3.bw
THP1	H3K27me3	m2	/PATH/TO/DIR/H3K27me3.bw
THP1	H3K27me3	m3	/PATH/TO/DIR/H3K27me3.bw
```

The file with the difference between the output files I got when I set threads=1 and the output file I got when I set threads=10 has a specific pattern of names: `${cell}_m1.${marker}.S3V2.bedgraph.NBP.txt`.  I guess this information might help you find the problem.

In brief, there are 2 main issues:

1. If there are more than 1 thread, the first file in the output with the same marker in the same cell will have an error.
2. Even I set the thread>1, time consumed by s3norm is nearly identical to the case where it is set to 1.

**Comment by guanjue** [comment]
Thanks for this information. 

Yes, indeed, when there are too many threads for the memory to handle, some of the "bigwigaverageoverbed" parallel runs may be interrupted.

The time for the cross mark s3norm step is not paralleled so that is why there should not be differences in runs with different threads.

Best wishes.
Guanjue

**Comment by fatyang799** [comment]
There is one more piece of information I would like to share with you.

When I tested this code, I ran the script with both thread=1 and thread=4. I then checked the output file for both results.

The md5 values of the output files were the same for both runs, suggesting that perhaps I could set thread to 4.

However, in another run of my past data, I also set thread=4, but the output files from that run also had the NA value, which was confusing to me.
